# Generated by Django 2.2.7 on 2019-11-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant", fields=[("name", models.CharField(max_length=100, primary_key=True, serialize=False))]
        )
    ]
