language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements/test.txt
script:
  - cd app
  - coverage run --source='.' manage.py test
  - coverage report
after_success:
  - codecov