language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements/test.txt
script:
  - coverage run --source='app' app/manage.py test restaurants
  - coverage report
after_success:
  - codecov